version: '3'

services:
  postgres:
    image: postgres:17
    container_name: postgres_demo_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_demo:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'

volumes:
  postgres_demo:
